# Dependencies
markdown: rdiscount
pygments: true

# Permalinks
permalink: none

# Server
destination: ./_site
exclude: [".editorconfig", ".gitignore", "bower.json", "CNAME", "Gruntfile.js", "package.json", "node_modules", "README.md", "vagrant", ".vagrant"]
port: 9001
