blogTitle = "Stonelinks"
subTitle = "Homepage of Lucas Doyle"
blogUrl = "http://stonelinks.org/"
authorName = "Lucas Doyle"
authorBio = "Written by Lucas Doyle, a robotics engineer who does a lot of web development in San Francisco."
gaCode = "UA-18750328-2"
