blogTitle = "Stonelinks"
subTitle = "Homepage of Lucas Doyle"
blogUrl = "http://stonelinks.org/"
authorName = "Lucas Doyle"
authorBio = "Written by Lucas Doyle, a software engineer with a Robotics / GIS / UI focus in the SF Bay Area"
gaCode = "UA-18750328-2"

[socialNetworks]
github = "https://github.com/Stonelinks"
linkedin = "http://www.linkedin.com/pub/lucas-doyle/25/550/169"
youtube = "https://www.youtube.com/c/LukeDoyle0"
# youtube = "http://www.youtube.com/user/RealStonelinks"
dribbble = "https://dribbble.com/Stonelinks"
